version: "3.9"
services:
  worker:
    build: .
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
    ports:
      - "3000:3000"  
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_ID: ${SESSION_ID}
      REMOVEBG_KEY: ${REMOVEBG_KEY}
      PREFIX: ${PREFIX}
      OWNERS: ${OWNERS}
      OMENTION: ${OMENTION}
      BOTNAME: ${BOTNAME}
      PACKNAME: ${PACKNAME}
      AUTHOR: ${AUTHOR}
      MENUVID: ${MENUVID}
      IGFG: ${IGFG}
      FGYT: ${FGYT}
      FGPYP: ${FGPYP}
      FGLOG: ${FGLOG}
      THUMB: ${THUMB}
      OWNERIMG: ${OWNERIMG}
  redis:
    image: redis
volumes:
  logvolume01: {}
